# Function to count occurrences of each nucleotide in a DNA string
def count_nucleotides(dna_string):
    
    # Initialize counters for each nucleotide
    count_A = dna_string.count('A')
    count_C = dna_string.count('C')
    count_G = dna_string.count('G')
    count_T = dna_string.count('T')
    
    # Sample DNA string provided in the problem
    return f"{count_A} {count_C} {count_G} {count_T}"

# Please Put Your Sample dataset in the
sample_input = "CAGGATATAAGACACCTTTAATTCTCACCTTGCATTAGTGAGCTCGTAGAACTTGTTTAATCTGGCACTCAATTTAACATATACGAAAAGAGATGAAGTGGATTTTATAGGTAGGACATCTTAGATTGCGGCCTGTGGCTCATTTCCACAGAGGGTGGCGCCGCGCCAGAATCCTTATCTCGATCTCTGCGCCTAGTTTTACAGCTTAAAGTAGCTGTAGGCAATGATACGTCTACCGTTTTTGATACAATTTCTCGACCGAATTCTTCGAAGACTGGCGCTTACGCAGGGGACGATCTTAGTGGGTCTTTTTCAAATGGCAATCTTGACAACCGGCAGCTAAGTGTGTCAAGCTAGATAGTGGCCTCACAGCATGATGTGCGCAGAATGGATCTGGGTACACCGTCAGACGTTCCAAGCCCGCACCCGTACAGGCCCAGAAACTCCAAATCCAATGGATCTGTTATGCGTGGCCTTGGGGTAACCCACAGGGTGTCTCAGCTGCCAATGCCACAGGTCAATTGCCCGGCGCCATGAACGCTTAAGTCCCATCGACATTGCCTCCAGTACGACCTCGTGATAGGTCCCGTTCGCCACTCGCAATTCTCGAAGGCTGTGTTTAGTTTGTCCGTTCCACTTCGCATATACACAGCGACAGATACACGTAGTAGGGACCGAAGGTTACCTACAGCAGAGGCGTCGGTAGGGCGCGTAAACGTGAGCAATTTGAAGGCCGTTACTGTCACGCGATCGGGGAGACCGGATCATGCATTCTAAAATCACTCATCACCGCACAAACCTGGTGGACTTACTTAGTCCAGTGGTGAGAATTTATCATAGATATATGGAGAACGTGATAGTGATGGCGGACGGACACTTGGTGACTTTAATAAGTGTACAACTTT"
# Call the function with the sample DNA string and print the result
result = count_nucleotides(sample_input)
print(result)